services:
  dlt:
    build:
      context: .
      dockerfile: dockerfile-dlt
    volumes:
      - ./data/tennisdb.duckdb:/data/tennisdb.duckdb
      - ./dlt_project:/app/dlt_project
    stdin_open: true  # interactive session
    tty: true         # open terminal
    command: python dlt_project/pipeline.py

  dbt:
    build:
      context: .
      dockerfile: dockerfile-dbt
    volumes:
      - ./data/tennisdb.duckdb:/data/tennisdb.duckdb
      - ./dbt_project:/app/dbt_project
    stdin_open: true  # interactive session
    tty: true         # open terminal
    depends_on:
      dlt:
        condition: service_completed_successfully  # Ensure dlt finishes before dbt
    command: dbt build

  streamlit:
    build:
      context: .
      dockerfile: dockerfile-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_project:/app/streamlit_project
    stdin_open: true
    tty: true
    depends_on:
      dbt:
        condition: service_completed_successfully  # Ensure dbt finishes before streamlit
