services:
  dlt:
    build:
      context: .
      dockerfile: dockerfile-dlt
    volumes:
      - ./data/tennisdb.duckdb:/data/tennisdb.duckdb
      - ./dlt_project:/app/dlt_project
    stdin_open: true  # interactive session
    tty: true         # open terminal
    command: python dlt_project/pipeline.py

  dbt:
    build:
      context: .
      dockerfile: dockerfile-dbt
    volumes:
      - ./data/tennisdb.duckdb:/data/tennisdb.duckdb
      - ./dbt_project:/app/dbt_project
    stdin_open: true  # interactive session
    tty: true         # open terminal
    command: dbt build

  streamlit:
    build:
      context: .
      dockerfile: dockerfile-streamlit
    volumes:
      - ./data/tennisdb.duckdb:/data/tennisdb.duckdb
      - ./streamlit_project:/app/streamlit_project
    ports:
      - "8501:8501"
    stdin_open: true  # interactive session
    tty: true         # open terminal
    command: bash
