FROM python:3.10-slim

WORKDIR /app

COPY ./dataload/ ./dataload

RUN pip install python-dotenv
RUN pip install duckdb
RUN pip install pydantic
RUN pip install requests
RUN pip install pandas

CMD ["bash"]
