FROM python:3.10-slim

WORKDIR /app/streamlit_project/

COPY ./streamlit_project/ ./streamlit_project

RUN pip install streamlit
RUN pip install pandas
RUN pip install duckdb

# Expose the Streamlit port
EXPOSE 8501

#CMD ["streamlit", "run", "/app/streamlit_project/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
CMD ["bash"]