dbt_project:
    target: dev
    outputs:
        dev:
            type: duckdb
            path: /data/tennisdb.duckdb
            schema: dbt_tennis
            extensions:
                - parquet